microSALT/cli.py, microSALT/server/templates/project_page.html, microSALT/server/templates/report_page.html, microSALT/server/views.py, microSALT/store/db_manipulator.py, microSALT/store/lims_fetcher.py, microSALT/utils/job_creator.py, microSALT/utils/renamer.py, microSALT/utils/scraper.py
Added rename script, pipeline handles other file formats, cleaned up, organism check.
Rename script needs to be cleaned up, but as always I'm in a bit of a rush.
=> Rename script and some other nice stuff

microSALT/server/templates/report_page.html
Thresholds are now properly managed in report.
=> Syncing bugfix

README.md, configExample.json, microSALT/cli.py, microSALT/server/templates/report_page.html, microSALT/store/db_manipulator.py, microSALT/utils/job_creator.py, microSALT/utils/scraper.py
Automatic e-mail on analysis finish
QUAST performs QC on samples. Unlinked atm.
Bugfixed viewer
Stdout set to 'info' log level. Some messages improved.
report page refactored
'Sample create' now works as a slim project create
=> E-mail and other things

MANIFEST.in, microSALT/__init__.py, microSALT/cli.py, microSALT/server/templates/report_page.html, microSALT/server/views.py, microSALT/store/db_manipulator.py, microSALT/store/lims_fetcher.py, microSALT/store/orm_models.py, microSALT/utils/job_creator.py, microSALT/utils/reporter.py, microSALT/utils/scraper.py
* Added resistance finding support
* Fixed non-develop installation
* Added license
* Envvar now takes priority over standard config path
* Replaced e-value with span metric
* Minor report reorganization
* Removed csv creation
* Reordered code
=> Added resistance genes, span support. post validation

README.md, configExample.json, microSALT/__init__.py, microSALT/cli.py, microSALT/server/templates/report_page.html, microSALT/server/views.py, microSALT/store/db_manipulator.py, microSALT/utils/job_creator.py, microSALT/utils/reporter.py, microSALT/utils/scraper.py
- Flag to set personal e-mail
- Flag for path, otherwise use infolder prefix to keywords
- Rerun flag
- Make analysis command use predef path
- Create 'start is now finished' file
- Add slurm logs to analysis folder
- Old samples have debug span and show as undef.
- Updated readme 
- Updated example config
- Sort resistance genes
=> Loads of bioinformatical commands

microSALT/__init__.py, microSALT/cli.py, microSALT/utils/reporter.py
Utility function with little use. Outputs html report in a specialized csv format.
=> CSV expansion

microSALT/__init__.py, microSALT/cli.py, microSALT/server/templates/report_page.html, microSALT/server/views.py, microSALT/store/db_manipulator.py, microSALT/store/lims_fetcher.py, microSALT/store/models.py, microSALT/utils/job_creator.py, microSALT/utils/referencer.py, microSALT/utils/scraper.py
**Major changes:**
- Proper novel alleles are now categorized with a running number at -10 and below
- Resistance type now works 100% of the time, falling back on file name
- Indexing of resistance databases will now never fail
- Novel alleles moved to error code -2
- File checker now also checks for invalid symlinks
- MLST is no longer established on prior BLAST filter
**Minor integrations from master:**
- Novel (x alleles) no longer display debug info
- Expanded ctrl category, orgs w/o pubmlst ref marked as unavailable
=> Step 1 of ST establishment

microSALT/server/templates/STtracker_page.html, microSALT/store/lims_fetcher.py, microSALT/store/orm_models.py, microSALT/utils/job_creator.py
Fetches Customer ID into database so that ST tracker can filter by it. Small, and somewhat urgent.
=> Customer ID extraction

install.sh, microSALT/__init__.py, microSALT/cli.py, microSALT/utils/job_creator.py
Backroll of scratch writing, to make the code hasta compatible.
Also minor improved exception handling for poor configs.
=> Hasta integration

microSALT/__init__.py, microSALT/cli.py, microSALT/utils/reporter.py
This PR stores report files. Analysis files automatically, and custom reports on demand.
**How to test**:
On hasta:
1. Pull branch into /home/proj/stage/bin/git/microSALT
2. us
3. source activate S_microSALT
4. pip install .
5. microSALT utils report (project) --type (ALL OF THEM) --output (PATH) --email (YOUREMAIL)
6. microSALT utils report (project) --type (ONE  OF THEM) --email (YOUREMAIL)
**Expected outcome**:
For case 5, a report file should appear in the given (PATH)
For case 6, no report file should appear in the folder you stand in 
After completion, attach a screenshot with the filenames of the generated files.
**Review:**
This is minor **version bump** because the code can't alter the results in a mysterious way; is backwards compatible, and will either outright crash or not …
=> Report storage

microSALT/__init__.py, microSALT/server/templates/alignment_page.html, microSALT/server/templates/typing_page.html, microSALT/store/db_manipulator.py
The features of this PR primarily concerns minor bug fixes for bioinformaticians.
* Novel ST incorrectly displayed as negative instead of I(number) in one area.
* Priority, method and dates were assumed to always exist; thus disallowing report generation until project was reanalysed.
=> Stability for latest typing report

microSALT/__init__.py, microSALT/server/templates/alignment_page.html, microSALT/server/templates/typing_page.html, microSALT/server/views.py, microSALT/store/db_manipulator.py, microSALT/store/lims_fetcher.py, microSALT/utils/job_creator.py, microSALT/utils/reporter.py, microSALT/utils/scraper.py
The features of this PR primarily concerns bioinformaticians
* Rerun flag no longer collides with Reports table
* QC report: Unavailable Application Tag is now displayed in red
* QC report: Unavailable date now shows 'Okänd' instead of date.min
* Reports: Translated Unknown to Okänd for novel alleles in report
* Trimmed the warning message for data already existing in database
* Removed legacy value date_received (date of LIMS project opening), superseeded by date_arrival
Samples containing the new organism S. pneumoniae was incorrectly labelled as containing K. pneumoniae due to lax string comparison, and a lack of databases for the former. Upon using the rerun flag, the automatic version management disallowed the rerun flag to delete old entries.
In addition to this, multiple minor …
=> Rerun flag reimplementation

install.sh
Updates related to the installation script, which doesn't affect the core microSALT package.
=> install.sh update

microSALT/__init__.py, microSALT/store/lims_fetcher.py
This feature disallows users from inputting leading spaces in the microbial reference.
This would crash the entire QC workflow.
=> Stripping user input in response to issue

microSALT/__init__.py, microSALT/store/db_manipulator.py
Changed resync to display samples with error code -1 to -4
Changed resync to completely ignore samples with pubMLST code 0.
Resync is until further notice only used by me, and code changes affect nothing currently in production
=> Resync function updates

.gitignore, .travis.yml, configExample.json, microSALT/__init__.py, requirements-dev.txt, tests/test_commands.py, tests/test_config.py
The features of this PR primarily concern internals.
It only adds a basic functional pytest and cleans up the example config.
Testing is resolved exclusively through Travis-CI integration, since no existing python files are modified.
=> Added pytest and cleaned up example config

.gitignore, .gitlint, .travis.yml, configExample.json, microSALT/__init__.py, microSALT/cli.py, tests/test_commands.py, tests/test_config.py, tests/test_webserver.py
The features of this PR primarily concerns internals.
Testing is resolved exclusively through Travis-CI integration, since no existing python files are modified.
=> Expanded testing. init now initializes logger, auto-creates directories

.travis.yml, install.sh, microSALT/__init__.py
The features of this PR primarily concerns internals
Fixed a bug that disallowed release installations to select branch.
Also made installation script travis compatible by giving it meaningful --yes options.
Since test only concerns installer script, testing is automatically handled through pytest in travis.
The PR Travis test will fail in this PR, however the branch has to be successful. In the future both will be successful.
=> Install script travis compatible

microSALT/__init__.py, microSALT/utils/reporter.py
Resolves issue #108 
Additionally:
- up
- microSALT utils report /home/proj/production/microbial/queries/ACC7105.json --type json_dump --output ~ --email 2@2.com
- Check that file is corrected in accordance with #108 
File is corrected in accordance with #108
=> Deliverables file fix

README.md
_##Remove elements in cursive as needed.##_
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh BRANCHNAME`_
- _`us`_
- _(SITUATIONAL) `export MICROSALT_CONFIG=/home/proj/dropbox/microSALT.json`_
- _Select a relevant subset of the following:_
- _`microSALT analyse project MIC4107`_
- _`microSALT analyse project …
=> Fix reportfolder

microSALT/utils/reporter.py, tests/test_database.py, tests/test_reporter.py
Added tests to test_database.py and test_reporter.py
_The update only concerns self tests, it is sufficient to rely on the development testing along with the Travis self-test automatically applied to the PR._
_The results from Travis indicate that this PR is ready to be merged._
=> Adding self tests

microSALT/cli.py, microSALT/utils/referencer.py
_The features of this PR primarily concerns bioinformaticians_
* Bug fix for ncbi reference download
* Updated pubmlst external reference download
* Added force_update flag for analyse command
The pubmlst website was updated and those mlst profiles that were only linked to pubmlst could therefore not be updated. 
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh fix_referencer`_
- _`us`_
- _`cg workflow microsalt config-case -t 244354`_
- _`Remove the following references from the stage genomes directory: NC_016845.1  and NC_011751.1`_
- _`microSALT analyse …
=> Updated and fixed bugs in pubmlst and ncbi downloads

microSALT/__init__.py, microSALT/utils/job_creator.py
Fixed a bug when running bad sample.
=> Fixed a bug when running bad sample.

microSALT/__init__.py, microSALT/utils/job_creator.py
=> slurmid hotfix

DEPLOYMENT.md, microSALT/__init__.py
=> Add deployment

microSALT/utils/pubmlst/client.py, microSALT/utils/pubmlst/helpers.py, microSALT/utils/referencer.py
_##Remove elements in cursive as needed.##_
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/install-microsalt-stage.sh BRANCHNAME`_
- _`us`_
- _`conda activate S_microSALT`_
- _(SITUATIONAL) `export MICROSALT_CONFIG=/home/proj/dropbox/microSALT.json`_
- _Select a relevant subset of the following:_
- _`microSALT analyse project MIC4107`_
- _`microSALT analyse project …
=> Added skip & retry mechanism for irrelevant/failed authentication 

.github/workflows/run_tests.yml, configExample.json, microSALT/__init__.py, microSALT/cli.py, microSALT/store/models.py, microSALT/utils/job_creator.py, microSALT/utils/pubmlst/authentication.py, microSALT/utils/pubmlst/client.py, microSALT/utils/pubmlst/constants.py, microSALT/utils/pubmlst/exceptions.py, microSALT/utils/pubmlst/get_credentials.py, microSALT/utils/pubmlst/helpers.py, microSALT/utils/referencer.py, microSALT/utils/scraper.py, tests/test_config.py, tests/test_reporter.py
This is a patch of microSALT, fixing the authentication requests done to pubMLST and its databases.
- Authentication for the `fetch_external` function - #201
- OAuth authentication - replacing the custom OAuth header #198
- Fix updates of existing databases with the correct number of columns #203 
- Added skip & retry mechanism for irrelevant/failed authentication #205 
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/install-microsalt-stage.sh BRANCHNAME`_
- _`us`_
- _`conda activate S_microSALT`_
- _(SITUATIONAL) `export MICROSALT_CONFIG=/home/proj/dropbox/microSALT.json`_
- …
=> microSALT - v4.2.0
