configExample.json
microSALT/cli.py
microSALT/server/views.py
microSALT/utils/reporter.py
requirements.txt

- Removed weasyprint the HPC disagreed with it.
- Replaced PDF generation with HTML generation
- Both reports are now generated from shared function
- HTML automatically downloaded and e-mailed when finishing
- CSV now generated with correct name under input folder
- NTC sample prefix automatically declares the sample as 'control'

Improved report generation

---

README.md
configExample.json
install.sh
microSALT/__init__.py
microSALT/server/views.py
microSALT/store/lims_fetcher.py
microSALT/utils/reporter.py

This PR adds the following features:
- JSON is generated in runfolder when doing a normal analysis
- JSON now contains more QC data
- E-mailing from the nodes _might_ work now
- Novel alleles and Novel+Thresholds failed are now classed as Unknown
- Genologics config is now read from the microSALT config 
**How to test**:
On hasta:
0. If you have any files named *genologics* in your home directory. Temporarily rename them.
1. Pull branch into /home/proj/stage/bin/git/microSALT
2. us
3. source activate S_microSALT
4. export MICROSALT_CONFIG=/home/proj/dropbox/microSALT.json
4.1 doublecheck that the paths in /home/proj/dropbox/microSALT.json works for you
5. pip install .
6. microSALT analyse sample ACC5710A5 --email (email)
7. microSALT analyse project ACC5710 --email (email)
**Expected …

Last second fixes

---

microSALT/__init__.py
microSALT/store/lims_fetcher.py
microSALT/utils/job_creator.py
microSALT/utils/scraper.py

The features of this PR primarily concerns bioinformaticians
* microSALT now more aggressively checks the organism supplied
* microSALT now uses the unfiltered organism name more readily in reports
This change was prompted by S. pseudomonas incorrectly identifying as Kleb(s)iella pseudomonas.
microSALT analysis should be run on one of the misbehaving samples (ACC5746A8).
The log should warn about the exception, but both the Typing and QC report should report the correct organism (albeit the Typing report defaulting on about every data point since no pubMLST reference exists).
Both reports were successfully generated and contained the correct organism 'S. pseudomonas' instead of the previously incorrect 'Klebsiella pseudomonas' one.

Improved organism check

---

microSALT/__init__.py
microSALT/utils/job_creator.py

The features of this PR primarily concerns bioinformaticians
The changes in this PR guarantees that all input files are used for the microbial analysis to a greater degree.
The changes presented here were made in response to the identification that some projects did not have all input files included during analysis. This would in turn mean that microSALT underrepresented the amount of reads for "Total Reads".
_Basic test routine:_
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh verify_fix`_
- _`us`_
- _`microSALT analyse sample ACC5955A9`_
Verify that the results for projects MIC3109 are consistent with those presented to those attached in AMSystem doc 1490:9 section …

HOTFIX: Improved fastq-file inclusion for analysis

---

microSALT/__init__.py
microSALT/cli.py
microSALT/server/templates/alignment_page.html
microSALT/server/templates/typing_page.html
microSALT/store/db_manipulator.py
microSALT/utils/referencer.py

The features of this PR primarily concerns bioinformaticians
* The command `microSALT utils resync review` now defaults to list format
* Minor changes to the contact information in the reports
* `microSALT utils resync overwrite` now has a `--force` flag
* Insert Size now displays properly for values failing the threshold.
These functions are specialized and not part of normal production routine.

Resync and contact updates

---

microSALT/__init__.py
microSALT/server/templates/alignment_page.html

_The percentage of ordered reads in the 'Antal Reads' column of the QC-report showed incorrect numbers. This was due to reads vs. read pairs confusion regarding the information in the apptags._
_The percentage of ordered reads will now be divided by 2._
_This is a description of the tests necessary to verify the stability of the PR._
_Basic test routine:_
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh pct_reads_fix`_
- _Select installer options "S_microSALT" , "release" and "pct_reads_fix"_
- _`us`_
- _`export MICROSALT_CONFIG=/home/proj/dropbox/microSALT.json`_
_Verify that the …

Fix percentage of ordered reads in QC-report

---

microSALT/utils/scraper.py

The features of this PR primarily concerns internals.
When scraping resistance: version of gene bank ID was not picked up, crashing microSALT. Hotfix fixes this.
Test run problematic sample, ACC6417A121.
Expected outcome: report with typical results generated.
This being a hotfix, all other tests are considered covered by Travis self tests.

resistance regex supports references version

---

microSALT/store/db_manipulator.py
microSALT/utils/scraper.py
requirements.txt

The features of this PR primarily concerns end-users.
When duplicate loci hits occur, only the best hit is displayed. Prior all loci hits were shown, which could be considered a debugging behaviour.
This is changed due to being explicitly requested, as to decrease confusion regarding results.
The update is a hotfix, it is sufficient to rely on the development testing along with the Travis self-test automatically applied to the PR.
Travis CI PR test may display difficulties due to the master branch running an incompatible click version.
_These are the results of the tests, and necessary conclusions, that prove the stability of the PR._

Duplicate loci hits are now obfuscated

---

microSALT/__init__.py
microSALT/utils/referencer.py
microSALT/utils/scraper.py

The features of this PR primarily concerns end-users.
It resolves the issue of non-pubMLST compatible organisms (e.g. research samples) not correctly displaying their organism in the final report.
The update is a hotfix, it is sufficient to rely on the development testing along with the Travis self-test automatically applied to the PR.

Proper display of non pubMLST-compatible organisms

---

microSALT/utils/referencer.py
requirements-dev.txt
requirements.txt

The features of this PR primarily concerns internals.
Summary of the changes made:
Due to changes at pubmlst.org; microSALT was unable to gather the version number for external references. This is now resolved.
_Additional testing routine to verify the stability of the PR:_
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh fix_referencer`_
- _`us`_
- Download/copy the existing profile and loci files for Klebsiella pseudomonas
- cg workflow microsalt config-case ACC6369A43
- microSALT analyse /home/proj/stage/microbial/queries/ACC6369A43.json --input …

HOTFIX: Fetch reference version number for external references

---

microSALT/__init__.py
microSALT/utils/job_creator.py
microSALT/utils/reporter.py
microSALT/utils/scraper.py

* Output files for delivery are named with sample ID
* Paths in deliverables file updated and changed accordingly
* Files in housekeeper need unique names
- `bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh add_output_prefix`
-  `us`
- `source activate S_microSALT`
- `microSALT analyse /home/proj/stage/microbial/queries/ACC5551.json --input /home/proj/stage/microbial/fastq/ACC5551`
- `microSALT analyse …

Add output prefix

---

microSALT/__init__.py
microSALT/utils/scraper.py

* Improved backwards compatibility for QUAST files and old resFinder resistance reference files.
This improvement was made in order to re-run ALL old analysis.
Tests are self-evident as the fix was used to successfully re-run all old data.

Attempt to make resistance searches more compatible

---

microSALT/__init__.py
microSALT/utils/job_creator.py

_The features of this PR primarily concerns **internals**_
- A yaml file containing submitted slurm jobs is saved in reports/trailblazer and analysis output directories. This file will enable progress tracking of Microsalt analyses with Trailblazer
- The need to make production life easier by displaying ongoing analyses and their status in Trailblazer
PR is fully backwards compatible with no changes done to workflow logic
starting with CG works as it always did:
```
[10|11|345] 2z [maryia.ropart@hasta:/home/proj/stage/microbial/results/reports/trailblazer] [S_main] $ cg workflow microsalt start bigdrum
Saved config /home/proj/stage/microbial/queries/bigdrum.json
Running command source activate …
```

Save job_ids.yaml file for trailblazer tracking

---

microSALT/utils/referencer.py

Some organisms on pubMLST did not have the MLST scheme as the first scheme. MicroSALT downloads therefore exited with HTTP errors and was unable to update the data for some organisms.  
- Adapted query paths for MLST downloads, considering the variability.

Fixed bug in mlst download for some organisms

---

microSALT/utils/referencer.py

Issues with downloading some references hosted at pubMLST. The main issue is that references are labelled inconsistently by pubMLST. This PR updates the search for correct href links on pubMLST.
- bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-microsalt-stage.sh fix_MLST_oxford
- us
- source activate S_microSALT
- Start analysis of ACC5551
- Ensure that MLST references are updated

Updated pubMLST download links

---

microSALT/server/templates/alignment_page.html
microSALT/server/templates/typing_page.html

Implements a commit from #125 to remove swedac logo for non-accredited analyses.
_These are the results of the tests, and necessary conclusions, that prove the stability of the PR._
See comments

fix(SWEDAC) SWEDAC logo only on MW samples

---

microSALT/utils/reporter.py

The quality control implemented in cg fails for microsalt due to the duplication rate not being reported in the json output.

Fix missing duplication rate in json report

---

microSALT/server/templates/STtracker_page.html
microSALT/server/templates/alignment_page.html
microSALT/server/templates/typing_page.html

See full description in #183 .
This PR simply removes the metric from the Typing HTML report.
It does NOT remove the underlying `contig_coverage` metric from the database model or the other parts of the code.
Two minor additional edits:
- Hard-coded widths are removed from MLST and Resistance columns, as they were causing the "Grupp" column to be too narrow at times.
- Swedish characters (åäöÅÄÖ) are replaced with their corresponding HTML codes to avoid encoding issues on some computers.
The MLST and Resistance sections in the Typing report are what is primarily affected.
Below follows before and after screenshots of a (the same) representative section:
Before (with the later removed column highlighted):
After:

Fix #183: Remove potentially consufing "Kmer täckning" columns

---

microSALT/utils/scraper.py

This PR fixes issue #185 , which through testing has been shown to be due to a combination of factors:
1. The introduction, in february 2023, in the ResFinder database of an ["all" file (`all.fsa`)](https://bitbucket.org/genomicepidemiology/resfinder_db/src/master/all.fsa) in combination with the other files with resistance genes, meaning the genes are duplicated in the ResFinder database.
2. The fact that we changed a comparison method in microSALT for the microSALT release that would earlier remove also identical duplicates, but which does no longer do that (see the change [here](https://github.com/Clinical-Genomics/microSALT/commit/edb92569491ed8a9c5e7a75f16f6e9a0e0f549f9#diff-79fdcbc666e5174e549ad4bbaab91c2cb894478346827f3b624e82fa719a8426L394)).
The effect of the change in 2. above …

Fix #185: Add back more greedy elimination of similar results

---

microSALT/store/models.py
microSALT/utils/referencer.py

This PR tries to adress the issue that when we download databases and try to update existing ones we have the clonal complex and species column. Two columns that are not used in the analysis.
* [`microSALT/store/models.py`](diffhunk://#diff-2aa8f114d897cc9e9ea718c9c3f23ed8177e35c319b4bf19c1a81b4c96b3d5caL22-R37): Simplified the formatting of error messages and file handling to improve readability. [[1]](diffhunk://#diff-2aa8f114d897cc9e9ea718c9c3f23ed8177e35c319b4bf19c1a81b4c96b3d5caL22-R37) [[2]](diffhunk://#diff-2aa8f114d897cc9e9ea718c9c3f23ed8177e35c319b4bf19c1a81b4c96b3d5caL69-L93)
* [`microSALT/store/models.py`](diffhunk://#diff-2aa8f114d897cc9e9ea718c9c3f23ed8177e35c319b4bf19c1a81b4c96b3d5caL22-R37): Limited the number of elements considered in the header to the first 8 elements to …

Fix-pubmlst-query-insert

---

.github/workflows/run_tests.yml
configExample.json
microSALT/__init__.py
microSALT/utils/pubmlst/authentication.py
microSALT/utils/pubmlst/client.py
microSALT/utils/pubmlst/constants.py
microSALT/utils/pubmlst/exceptions.py
microSALT/utils/pubmlst/get_credentials.py
microSALT/utils/pubmlst/helpers.py
microSALT/utils/referencer.py
tests/test_config.py

_##Remove elements in cursive as needed.##_
- _`bash /home/proj/production/servers/resources/hasta.scilifelab.se/install-microsalt-stage.sh BRANCHNAME`_
- _`us`_
- _`conda activate S_microSALT`_
- _(SITUATIONAL) `export MICROSALT_CONFIG=/home/proj/dropbox/microSALT.json`_
- _Select a relevant subset of the following:_
- _`microSALT analyse project MIC4107`_
- _`microSALT analyse project …

adding modality for queries towards pasteur database
